/* tslint:disable */
/* eslint-disable */
/**
 * Sparely API
 * API for Sparely
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface CreatePaymentDto
 */
export interface CreatePaymentDto {
    /**
     * 
     * @type {number}
     * @memberof CreatePaymentDto
     */
    amount: number;
    /**
     * 
     * @type {string}
     * @memberof CreatePaymentDto
     */
    campaignId: string;
}
